apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    uid: victoriametrics
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 3s
      prometheusType: Prometheus
      prometheusVersion: 2.48.0
